/**
 * Prompt construction for the patcher's coding agent.
 *
 * The agent is told:
 *   - what bug a probe agent reproduced (intent + reasoning + heuristic detail)
 *   - the exact action sequence (so it can correlate to specific UI flows)
 *   - what file paths it MUST NOT touch
 *   - that it ships one fix on a feature branch — no merging, no extra refactors
 *
 * The agent's tools (Read/Edit/Bash/Glob/Grep) are restricted by the SDK's
 * allowedTools config in orchestrator.ts.
 */

import type { PatcherContext } from './types'

const DEFAULT_DENYLIST = [
  '.github/workflows/',
  '.env',
  '.env.local',
  '.env.production',
  'infra/',
  'deploy/',
  // glob-like name patterns the agent should self-enforce
  '*secret*',
  '*credential*',
]

export type BuiltPrompt = {
  systemPrompt: string
  userPrompt: string
  /** Written to /workspace/error_context.json so the agent can re-read mid-task. */
  errorContextJson: string
}

export function buildPrompt(ctx: PatcherContext): BuiltPrompt {
  const denylist = [...DEFAULT_DENYLIST, ...(ctx.targetRepo.pathDenylist ?? [])]

  const systemPrompt = `You are a careful senior engineer fixing one specific bug in a real codebase.
The repo has been freshly cloned to your working directory. You have Read, Edit, Glob, Grep, and Bash tools.

YOUR JOB
1. Understand the bug from the report below + by reading the relevant code.
2. Make the smallest, most targeted fix that addresses the root cause.
3. If you need to verify, run the project's tests/typechecker via Bash. Do not invent commands.
4. When done, exit. Do NOT commit or push — the orchestrator handles that.

NON-NEGOTIABLE RULES
- Do NOT modify any of these paths: ${denylist.join(', ')}.
- Do NOT add new dependencies unless absolutely necessary; if you must, justify in a code comment.
- Do NOT broaden scope: no opportunistic refactors, no "while I'm here" cleanups, no doc rewrites.
- Do NOT touch CI configuration or secrets.
- Prefer changing one or two files over scattering edits across many.
- Match the existing code style. Read neighboring code first.
- If the fix is ambiguous and you'd be guessing, leave a clear comment near the affected code
  explaining what you observed and exit without editing — a human will take it from here.

The full bug report is at /workspace/error_context.json. Read it before you start.`

  const userPrompt = `Bug report

Intent: ${ctx.intent.name} — ${ctx.intent.description}
Verdict: ${ctx.verdict}
Heuristic detail: ${ctx.bugDetail}
Probe agent's reasoning: ${ctx.verdictReasoning}
Target URL the probe was hitting: ${ctx.targetUrl}

The reproduction (the exact sequence of actions the probe took) and any
captured network/console errors are in /workspace/error_context.json.

Start by reading that file, then explore the repo to find the relevant
code. Make the fix. Then exit.`

  return {
    systemPrompt,
    userPrompt,
    errorContextJson: JSON.stringify(ctx, null, 2),
  }
}

/** PR title — short, prefixed, traceable. */
export function buildPrTitle(ctx: PatcherContext): string {
  const short = ctx.bugDetail.slice(0, 60) || ctx.intent.name
  return `[auto-fix] ${short}`
}

/** PR body — structured markdown. Includes the DO NOT MERGE notice. */
export function buildPrBody(ctx: PatcherContext, opts: { runUrl: string; diffSummary: string }): string {
  const reproJson = JSON.stringify(ctx.reproduction, null, 2)
  return `> [!WARNING]
> **DO NOT MERGE WITHOUT REVIEW** — this PR was opened by an autonomous agent.

## What

A probe found a bug in fork \`${ctx.forkId}\` of [run ${ctx.runId}](${opts.runUrl}).
This PR is the patcher agent's attempt at a fix.

## Bug report

- **Adversarial intent:** \`${ctx.intent.name}\` — ${ctx.intent.description}
- **Heuristic detail:** ${ctx.bugDetail}
- **Probe agent reasoning:** ${ctx.verdictReasoning}

## Reproduction

The probe agent took the following actions against \`${ctx.targetUrl}\`:

\`\`\`json
${reproJson}
\`\`\`

## Diff summary

${opts.diffSummary}

---

*Generated by the Parallel Agents patcher. Review carefully — the agent's
edit history is in the run dashboard linked above.*`
}
